package com.rfsentinel.app.detect

import java.io.BufferedReader
import java.io.InputStream
import java.io.InputStreamReader

/**
 * Offline lookup tables generated by tools/gen_assets.py from the IEEE
 * registry (MA-L/MA-M/MA-S) and the Bluetooth SIG assigned numbers. Loaded once
 * off the main thread; every lookup returns null until loading finishes.
 */
object VendorDb {

    /** Hex prefix (6, 7 or 9 nibbles) -> registrant. */
    @Volatile private var oui: Map<String, String> = emptyMap()
    @Volatile private var companies: Map<Int, String> = emptyMap()
    @Volatile private var uuids: Map<Int, String> = emptyMap()
    /** (category shl 8 or subcategory, subcategory -1 stored as 0xFF) -> name. */
    @Volatile private var appearance: Map<Int, String> = emptyMap()

    @Volatile var loaded = false
        private set

    /** Loads all tables. [open] maps an asset file name to its stream. */
    @Synchronized
    fun load(open: (String) -> InputStream) {
        if (loaded) return
        oui = readTsv(open("vendors/oui.tsv")) { k, v -> k to v }
        companies = readTsv(open("vendors/bt_company.tsv")) { k, v -> k.toInt(16) to v }
        uuids = readTsv(open("vendors/bt_uuid16.tsv")) { k, v -> k.toInt(16) to v }
        val app = HashMap<Int, String>()
        BufferedReader(InputStreamReader(open("vendors/bt_appearance.tsv"), Charsets.UTF_8)).useLines { lines ->
            lines.filter { !it.startsWith("#") }.forEach { line ->
                val p = line.split('\t')
                if (p.size >= 3) {
                    val cat = p[0].toInt(16)
                    val sub = if (p[1] == "-") 0xFF else p[1].toInt(16)
                    app[(cat shl 8) or sub] = p[2]
                }
            }
        }
        appearance = app
        loaded = true
    }

    private fun <K> readTsv(stream: InputStream, map: (String, String) -> Pair<K, String>): Map<K, String> {
        val out = HashMap<K, String>()
        BufferedReader(InputStreamReader(stream, Charsets.UTF_8)).useLines { lines ->
            lines.filter { it.isNotEmpty() && !it.startsWith("#") }.forEach { line ->
                val tab = line.indexOf('\t')
                if (tab > 0) {
                    val (k, v) = map(line.substring(0, tab), line.substring(tab + 1))
                    out[k] = v
                }
            }
        }
        return out
    }

    /**
     * Registrant of a MAC address, checking the most specific block first
     * (MA-S 36-bit, MA-M 28-bit, MA-L 24-bit). Null for randomized/locally
     * administered addresses, whose leading bytes aren't a vendor block.
     */
    fun macVendor(mac: String): String? {
        val hex = mac.replace(":", "").uppercase()
        if (hex.length < 6) return null
        val msb = hex.take(2).toIntOrNull(16) ?: return null
        if (msb and 0x02 != 0) return null
        val table = oui
        return table[hex.take(9)] ?: table[hex.take(7)] ?: table[hex.take(6)]
    }

    fun company(id: Int): String? = companies[id]

    fun uuid16(short: Int): String? = uuids[short]

    /** Human description of a 16-bit GAP appearance value. */
    fun appearance(value: Int): String? {
        val cat = value ushr 6
        val sub = value and 0x3F
        val catName = appearance[(cat shl 8) or 0xFF] ?: return null
        val subName = if (sub != 0) appearance[(cat shl 8) or sub] else null
        return if (subName != null) "$catName - $subName" else catName
    }
}

/** Hex-prefix table with variable-length (24/28/36-bit) keys. */
class PrefixTable<T>(entries: Map<String, T>) {
    private val map = entries.mapKeys { it.key.replace(":", "").uppercase() }

    fun match(mac: String): Pair<String, T>? {
        val hex = mac.replace(":", "").uppercase()
        for (len in intArrayOf(9, 7, 6)) {
            if (hex.length < len) continue
            val key = hex.take(len)
            map[key]?.let { return key to it }
        }
        return null
    }
}
